#version: '3.8'
#
#services:
#  minha-app:
#    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
#    container_name: minha-app
#    restart: unless-stopped
#    ports:
#      - "8000:8000"
#    environment:
#      - ENVIRONMENT=production
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
#      interval: 30s
#      timeout: 5s
#      retries: 3
#      start_period: 10s